export {HomePage} from './HomePage/HomePage'
export {Categories} from './Categories/Categories'
export {SingleProduct} from './SingleProduct/SingleProduct'
export {AboutUs} from './AboutUs/AboutUs'
export {Cart} from './Cart/Cart'
export {Checkout} from './Checkout/Checkout'
export {Listings} from './Listings/Listings'
export {NotFound} from './NotFound/NotFound'
